theme: jekyll-theme-minimal
title: Md Nurullah Patwary
description: "Phone:: +8801720075715 
| email: ​noor.fahim1192@gmail.com 
| linkedIn: ​https://www.linkedin.com/in/noor-1192/ 
| Address: Eastern Rokeya Tower, 98 Boro Moghbazar, Dhaka-1217, Bangladesh. 
| Software engineering professional passionate for innovative engineering and crafted products."
